name: "Update with the latest schemes"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day

jobs:
  build-and-commit:
    uses: "tinted-theming/home/.github/workflows/shared-build-template-and-commit-themes.yml@main"
    permissions:
      contents: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      ref: ${{ github.head_ref }}
